### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by ghost** [sudharti/socify#17]

**Comment by scaffeinate** [comment]
@alex-jch Thanks a lot for notifying. Fixed and deployed 👍

**Comment by siax84** [comment]
it seems to have a problem again: "We're sorry but something went wrong" page comes.

**Comment by scaffeinate** [comment]
Fixed the issue https://github.com/sudharti/socify/commit/d3dc34fc0f9d509cca57b3c1f8bfccd92bf46ce6
