### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by heath3n** [sudharti/socify#18]
I tried uploading an image as a post and another as a profile picture and got the "We're sorry; something went wrong" message both times. I've tried with various file formats and sizes of images. Mentions also give me this error.

**Comment by scaffeinate** [comment]
@HEATH3N I am looking into the issue. Will be resolved shortly

**Comment by scaffeinate** [comment]
@HEATH3N I have changed from cloudinary to Amazon S3 for the image upload. Now everything should work fine.
