### ISSUE TITLE
Problem in Heroku Deploy

### ISSUE THREAD

**Issue by SINGHPRATAP** [sudharti/socify#19]
i am getiing this error while deploying my ruby app society -

ubuntu@ubuntu-HP-Compaq-dc7800p-Convertible-Minitower:~/society$ git push heroku master
Counting objects: 274, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (255/255), done.
Writing objects: 100% (274/274), 125.95 KiB | 0 bytes/s, done.
Total 274 (delta 51), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/.............
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Installing rake 11.2.2
remote:        Installing i18n 0.7.0
remote:        Installing json 1.8.3 with native extensions
remote:        Installing minitest 5.9.0
remote:        Installing thread_safe 0.3.5
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile2 2.1.0
remote:        Installing pkg-config 1.1.7
remote:        Installing rack 1.6.4
remote:        Installing mime-types-data 3.2016.0521
remote:        Installing arel 6.0.3
remote:        Installing acts_as_follower 0.2.1
remote:        Installing acts_as_commentable 4.0.2
remote:        Installing acts_as_votable 0.10.0
remote:        Installing bcrypt 3.1.11 with native extensions
remote:        Installing sass 3.4.22
remote:        Installing mimemagic 0.3.2
remote:        Installing coffee-script-source 1.10.0
remote:        Installing execjs 2.7.0
remote:        Installing thor 0.19.1
remote:        Installing concurrent-ruby 1.0.2
remote:        Installing orm_adapter 0.5.0
remote:        Installing multi_json 1.12.1
remote:        Using bundler 1.11.2
remote:        Installing jquery-atwho-rails 1.3.2
remote:        Installing mysql2 0.4.4 with native extensions
remote:        Installing rails_serve_static_assets 0.0.5
remote:        Installing rails_stdout_logging 0.0.5
remote:        Installing tilt 2.0.5
remote:        Installing turbolinks-source 5.0.0
remote:        Installing will_paginate 3.1.0
remote:        Installing tzinfo 1.2.2
remote:        Installing rdoc 4.2.2
remote:        Installing nokogiri 1.6.8 with native extensions
remote:        Installing rack-test 0.6.3
remote:        Installing warden 1.2.6
remote:        Installing mime-types 3.1
remote:        Installing bootstrap-sass 3.2.0.2
remote:        Installing coffee-script 2.4.1
remote:        Installing uglifier 3.0.1
remote:        Installing sprockets 3.7.0
remote:        Installing rails_12factor 0.0.3
remote:        Installing turbolinks 5.0.1
remote:        Installing activesupport 4.2.6
remote:        Installing sdoc 0.4.1
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing mail 2.6.4
remote:        Installing globalid 0.3.7
remote:        Installing activemodel 4.2.6
remote:        Installing jbuilder 2.6.0
remote:        Installing activejob 4.2.6
remote:        Installing activerecord 4.2.6
remote:        Installing carrierwave 0.11.2
remote:        Installing loofah 2.0.3
remote:        Installing rails-dom-testing 1.0.7
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Installing actionview 4.2.6
remote:        Installing actionpack 4.2.6
remote:        Installing actionmailer 4.2.6
remote:        Installing railties 4.2.6
remote:        Installing sprockets-rails 3.1.1
remote:        Installing coffee-rails 4.1.1
remote:        Installing font-awesome-rails 4.6.3.1
remote:        Installing responders 2.3.0
remote:        Installing jquery-rails 4.1.1
remote:        Installing public_activity 1.5.0
remote:        Installing rails 4.2.6
remote:        Installing sass-rails 5.0.6
remote:        Installing devise 4.2.0
remote:        Bundle complete! 23 Gemfile dependencies, 70 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Post-install message from rdoc:
remote:        Depending on your version of ruby, you may need to install ruby rdoc/ri data:
remote:        <= 1.8.6 : unsupported
remote:        = 1.8.7 : gem install rdoc-data; rdoc-data --install
remote:        = 1.9.1 : gem install rdoc-data; rdoc-data --install
remote:        >= 1.9.2 : nothing to do! Yay!
remote:        Bundle completed (25.55s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NameError: uninitialized constant AvatarUploader::Cloudinary
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/app/uploaders/avatar_uploader.rb:10:in `<class:AvatarUploader>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/app/uploaders/avatar_uploader.rb:3:in`<top (required)>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/app/models/user.rb:15:in `<class:User>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/app/models/user.rb:1:in`<top (required)>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `const_get'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in`block in constantize'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in`inject'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise.rb:301:in`get'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/mapping.rb:81:in `to'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/mapping.rb:76:in`modules'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/mapping.rb:93:in `routes'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/mapping.rb:160:in`default_used_route'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/mapping.rb:70:in `initialize'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise.rb:331:in`new'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise.rb:331:in `add_mapping'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:241:in`block in devise_for'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:240:in `each'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:240:in`devise_for'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/config/routes.rb:5:in `block in <top (required)>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in`instance_exec'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:410:in`draw'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/config/routes.rb:1:in `<top (required)>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in`block in load_paths'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `each'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in`load_paths'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:16:in `reload!'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:26:in`block in updater'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in `call'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in`execute'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:27:in `updater'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:7:in`execute_if_updated'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in`initialize!'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in`require_environment!'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/task.rb:62:in`block (2 levels) in define'
remote:        /tmp/build_2510ec9e0d74081dcb21a288068cdad0/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to societyapp.
remote: 
To https://git.heroku.com/societyapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/societyapp.git'
ubuntu@ubuntu-HP-Compaq-dc7800p-Convertible-Minitower:~/society$

**Comment by scaffeinate** [comment]
@SINGHPRATAP Sorry about that. I reached my maximum limit on Cloudinary. So had to switch to AWS. I will update the code asap. Thank you so much 👍

**Comment by scaffeinate** [comment]
@SINGHPRATAP Please do check if the 'cloudinary' gem in included in the Gemfile under production group.

**Comment by SINGHPRATAP** [comment]
Thnanks for your response.
But after switching to AWS and updae the code as yours i am getting same error.
