### ISSUE TITLE
sign up problem

### ISSUE THREAD

**Issue by SINGHPRATAP** [sudharti/socify#20]
![name blank](https://cloud.githubusercontent.com/assets/19155677/17897726/e3f7cef0-6972-11e6-9fab-d06a301e2678.png)

**Comment by scaffeinate** [comment]
@SINGHPRATAP Name there is a mandatory field while signing up. Can you please elaborate on the issue?

**Comment by scaffeinate** [comment]
@SINGHPRATAP If this is not an issue can you please close this one out?
