### ISSUE TITLE
Problem in Heroku Deploy

### ISSUE THREAD

**Issue by SINGHPRATAP** [sudharti/socify#21]
I apologize but its very important for me. Now i am getting this error while deploying.

ubuntu@ubuntu-HP-Compaq-dc7800p-Convertible-Minitower:~/society$ git push heroku master
Counting objects: 359, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (338/338), done.
Writing objects: 100% (359/359), 146.53 KiB | 0 bytes/s, done.
Total 359 (delta 98), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/.Retrying dependency api due to error (2/4): Bundler::MarshalError ArgumentError: marshal data too short
remote:        ........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Installing i18n 0.7.0
remote:        Installing CFPropertyList 2.3.2
remote:        Installing rake 11.2.2
remote:        Installing minitest 5.9.0
remote:        Installing json 1.8.3 with native extensions
remote:        Installing thread_safe 0.3.5
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile2 2.1.0
remote:        Installing pkg-config 1.1.7
remote:        Installing rack 1.6.4
remote:        Installing mime-types-data 3.2016.0521
remote:        Installing arel 6.0.3
remote:        Installing acts_as_commentable 4.0.2
remote:        Installing acts_as_follower 0.2.1
remote:        Installing acts_as_votable 0.10.0
remote:        Installing redcarpet 3.3.4 with native extensions
remote:        Installing rinku 1.5.1 with native extensions
remote:        Installing execjs 2.7.0
remote:        Installing aws_cf_signer 0.1.3
remote:        Installing bcrypt 3.1.11 with native extensions
remote:        Installing sass 3.4.22
remote:        Installing mimemagic 0.3.2
remote:        Installing unf_ext 0.0.7.2 with native extensions
remote:        Installing netrc 0.11.0
remote:        Installing coffee-script-source 1.10.0
remote:        Installing thor 0.19.1
remote:        Installing concurrent-ruby 1.0.2
remote:        Installing crass 1.0.2
remote:        Installing orm_adapter 0.5.0
remote:        Installing excon 0.52.0
remote:        Installing formatador 0.2.5
remote:        Installing multi_json 1.12.1
remote:        Installing ipaddress 0.8.3
remote:        Installing xml-simple 1.1.5
remote:        Installing inflecto 0.0.2
remote:        Installing trollop 2.1.2
remote:        Installing jquery-atwho-rails 1.3.2
remote:        Installing kgio 2.10.0 with native extensions
remote:        Installing pg 0.18.4 with native extensions
remote:        Installing populator 1.0.0
remote:        Using bundler 1.11.2
remote:        Installing rails_serve_static_assets 0.0.5
remote:        Installing rails_stdout_logging 0.0.5
remote:        Installing raindrops 0.17.0 with native extensions
remote:        Installing tilt 2.0.5
remote:        Installing will_paginate 3.0.7
remote:        Installing fission 0.5.0
remote:        Installing faker 1.6.6
remote:        Installing tzinfo 1.2.2
remote:        Installing nokogiri 1.6.8 with native extensions
remote:        Installing rack-test 0.6.3
remote:        Installing warden 1.2.6
remote:        Installing mime-types 3.1
remote:        Installing autoprefixer-rails 6.4.0.2
remote:        Installing uglifier 3.0.2
remote:        Installing auto_html 1.6.4
remote:        Installing bootstrap-sass 3.2.0.2
remote:        Installing coffee-script 2.4.1
remote:        Installing sprockets 3.7.0
remote:        Installing fog-core 1.42.0
remote:        Installing unf 0.1.4
remote:        Installing rails_12factor 0.0.3
remote:        Installing activesupport 4.2.6
remote:        Installing mail 2.6.4
remote:        Installing fog-json 1.0.2
remote:        Installing unicorn 5.1.0 with native extensions
remote:        Installing fog-local 0.3.0
remote:        Installing fog-vmfusion 0.1.0
remote:        Installing domain_name 0.5.20160615
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing globalid 0.3.7
remote:        Installing activemodel 4.2.6
remote:        Installing fog-aliyun 0.1.0
remote:        Installing fog-brightbox 0.11.0
remote:        Installing fog-openstack 0.1.11
remote:        Installing fog-sakuracloud 1.7.5
remote:        Installing fog-serverlove 0.1.2
remote:        Installing fog-softlayer 1.1.4
remote:        Installing fog-storm_on_demand 0.1.1
remote:        Installing http-cookie 1.0.2
remote:        Installing activejob 4.2.6
remote:        Installing activerecord 4.2.6
remote:        Installing carrierwave 0.11.2
remote:        Installing rails-dom-testing 1.0.7
remote:        Installing loofah 2.0.3
remote:        Installing fog-xml 0.1.2
remote:        Installing rbvmomi 1.8.2
remote:        Installing nokogumbo 1.4.9 with native extensions
remote:        Installing rest-client 2.0.0
remote:        Installing after_commit_action 1.0.1
remote:        Installing friendly_id 5.0.5
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Installing fog-atmos 0.1.0
remote:        Installing fog-cloudatcost 0.1.2
remote:        Installing fog-aws 0.11.0
remote:        Installing fog-dynect 0.0.3
remote:        Installing fog-ecloud 0.3.0
remote:        Installing fog-google 0.1.0
remote:        Installing fog-powerdns 0.1.1
remote:        Installing fog-profitbricks 0.0.5
remote:        Installing fog-rackspace 0.1.1
remote:        Installing fog-radosgw 0.0.5
remote:        Installing fog-riakcs 0.1.0
remote:        Installing fog-terremark 0.1.0
remote:        Installing fog-voxel 0.1.0
remote:        Installing fog-xenserver 0.2.3
remote:        Installing fog-vsphere 1.0.1
remote:        Installing cloudinary 1.2.3
remote:        Installing counter_culture 0.1.34
remote:        Installing actionview 4.2.6
remote:        Installing fog 1.38.0
remote:        Installing actionpack 4.2.6
remote:        Installing actionmailer 4.2.6
remote:        Installing railties 4.2.6
remote:        Installing sprockets-rails 3.1.1
remote:        Installing coffee-rails 4.1.1
remote:        Installing responders 2.3.0
remote:        Installing font-awesome-rails 4.6.3.1
remote:        Installing jquery-rails 4.2.1
remote:        Installing public_activity 1.5.0
remote:        Installing rails 4.2.6
remote:        Installing sass-rails 5.0.6
remote:        Installing devise 4.2.0
remote:        Installing sanitize 4.1.0
remote:        Bundle complete! 35 Gemfile dependencies, 125 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (60.16s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
**remote:        ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key**
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/fog-core-1.42.0/lib/fog/core/service.rb:244:in `validate_options'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/fog-core-1.42.0/lib/fog/core/service.rb:268:in`handle_settings'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/fog-core-1.42.0/lib/fog/core/service.rb:98:in `new'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/fog-core-1.42.0/lib/fog/core/services_mixin.rb:16:in`new'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/fog-core-1.42.0/lib/fog/storage.rb:27:in `new'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.11.2/lib/carrierwave/uploader/configuration.rb:83:in`eager_load_fog'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.11.2/lib/carrierwave/uploader/configuration.rb:96:in `fog_credentials='
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/config/initializers/carrierwave.rb:3:in`block in <top (required)>'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.11.2/lib/carrierwave/uploader/configuration.rb:118:in `configure'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.11.2/lib/carrierwave.rb:14:in`configure'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/config/initializers/carrierwave.rb:1:in `<top (required)>'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in`load'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in`load_dependency'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in`block in load_config_initializer'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in`load_config_initializer'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in`each'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`instance_exec'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in`block in run_initializers'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in`tsort_each_child'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in`initialize!'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`require'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in`load_dependency'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in`require_environment!'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/task.rb:62:in`block (2 levels) in define'
remote:        /tmp/build_8d794e2710d7b49a467b0718d04f77cd/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !   Push rejected to societyapp.
remote: 
To https://git.heroku.com/societyapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/societyapp.git'
ubuntu@ubuntu-HP-Compaq-dc7800p-Convertible-Minitower:~/society$ ^C

**Comment by briankung** [comment]
You have to set an `aws_access_key_id` and `aws_secret_access_key`, which are required for using AWS. It's likely that `socify` uses AWS to store assets.

You can most likely do this in your Heroku instance's environment variables.

**Comment by scaffeinate** [comment]
@briankung is right. I have moved to Amazon to store the assets. @SINGHPRATAP you could sign up for AWS and update the credentials or revert them to use cloudinary as before. Check this b42b9af1e5758d8577a4afb3c5a2eb42915937d7

**Comment by SINGHPRATAP** [comment]
thanks
