### ISSUE TITLE
Can't update posts

### ISSUE THREAD

**Issue by briankung** [sudharti/socify#23]
After looking into it briefly, it seems like the javascript targets `$('#new_post')`, which doesn't exist when editing a post. Thoughts on how to solve this?

**Comment by scaffeinate** [comment]
@briankung Thanks for notifying. Let me look into it.

**Comment by scaffeinate** [comment]
Fixed by 8900d0c4f9c283f035def6eb48441a47b3ff4f13

**Comment by scaffeinate** [comment]
Thank you 👍 @briankung
