### ISSUE TITLE
Event Calendar

### ISSUE THREAD

**Issue by enidedufresne** [sudharti/socify#3]
The event calendar only provides access to past dates, not future dates

**Comment by scaffeinate** [comment]
Used the same config for dob and event date pickers. Fixed it 13902567786f7eb39befd4734caf9466be5eb618. Deploying and closing the issue now :smile:

**Comment by enidedufresne** [comment]
You are amazing.

**Comment by scaffeinate** [comment]
Thanks a lot :grinning:
