### ISSUE TITLE
Photo Upload Error on Heroku but not development mode

### ISSUE THREAD

**Issue by ghost** [sudharti/socify#44]
hello, i get an error when trying to upload a photo to a status

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by scaffeinate** [comment]
@jrenna100 Something messed up the database on heroku. Reset the whole app. Should work fine now. Everything is getting moved to Amazon EC2 pretty soon once v2.0 is released.

**Comment by ghost** [comment]
i get this error

Expected(200) <=> Actual(403 Forbidden) excon.error.response :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>52FBE8EAC6C855E6</RequestId><HostId>Qh96EIXbKw0ARLlB3kQ/KGByEiarcWFTIRZYArWUV3BXSdvx9MV+2Pv8Mg2bGEaUbE3vY48Az10=</HostId></Error>" :cookies => [ ] :headers => { "Connection" => "close" "Content-Type" => "application/xml" "Date" => "Sat, 22 Apr 2017 19:02:15 GMT" "Server" => "AmazonS3" "x-amz-id-2" => "Qh96EIXbKw0ARLlB3kQ/KGByEiarcWFTIRZYArWUV3BXSdvx9MV+2Pv8Mg2bGEaUbE3vY48Az10=" "x-amz-request-id" => "52FBE8EAC6C855E6" } :host => "socify.s3.amazonaws.com" :local_address => "172.17.220.62" :local_port => 41094 :path => "/uploads/post/attachment/3/3J2Q9e.jpg" :port => 443 :reason_phrase => "Forbidden" :remote_ip => "52.216.32.96" :status => 403 :status_line => "HTTP/1.1 403 Forbidden\r\n"

**Comment by scaffeinate** [comment]
@jrenna100 You need to setup S3 credentials. I can see you didn't change the bucket name so it's trying to upload to my bucket. I added the instructions in the Readme. Please refer and close this issue.
![img_2513](https://cloud.githubusercontent.com/assets/1825853/25307754/ab7ff87a-2774-11e7-80e9-244e0480bf06.PNG)

**Comment by ghost** [comment]
sounds good thanks man!

**Comment by scaffeinate** [comment]
@jrenna100 👍
