### ISSUE TITLE
AWS Setup and Error

### ISSUE THREAD

**Issue by ghost** [sudharti/socify#47]
when trying to push to heroku master

remote:        rake aborted!
remote:        ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key

Please help ASAP

**Comment by scaffeinate** [comment]
@jrenna100 You need to obtain the AWS secret key and id form Amazon and update it in the ENV variables in Heroku. If you see the https://github.com/scaffeinate/socify/blob/master/config/secrets.yml there are the ENV variable names for id and key.

Here is how you can setup ENV variables on Heroku: https://devcenter.heroku.com/articles/config-vars#setting-up-config-vars-for-a-deployed-application

**Comment by ghost** [comment]
I tried this but i am still having issues. do i have to install any other gem for the aws?

**Comment by ghost** [comment]
Or am i not changing something somewhere else?

**Comment by ghost** [comment]
can i send you my version of project and information to help set it up with me? i can venmo or paypal you a donation if you can help me get this the way I would like. all i want to do from here is change some navigation (UI stuff) and make sure all functionality is good.

**Comment by ghost** [comment]
I emailed you as well with more information.

**Comment by ghost** [comment]
I can send you as well the Dropbox with vm and contents and logging in information

**Comment by scaffeinate** [comment]
@jrenna100 You could send me over your source code.I can help 👍

**Comment by ghost** [comment]
thank you, will email you the dropbox link

**Comment by ghost** [comment]
gotcha, check ur email too
