### ISSUE TITLE
Displaying html in newsfeed

### ISSUE THREAD

**Issue by sharanraj6** [sudharti/socify#48]
In Newsfeed the html tags like `&nbsp` and `<br>` etc. are displayed whenever there is a new activity
like this
![screenshot](https://cloud.githubusercontent.com/assets/28336608/26107183/0959c120-3a66-11e7-8c13-29722f0ba4f7.png)

**Comment by scaffeinate** [comment]
@sharanraj6 Thanks for the issue 👍 . Will fix this asap.

**Comment by scaffeinate** [comment]
@sharanraj6 Fixed this! https://github.com/scaffeinate/socify/commit/1ec49936b8b86f0b3bad1dfa8feb1e2f9381882d. Am closing this issue. Thanks!
