### ISSUE TITLE
Note error

### ISSUE THREAD

**Issue by moifouss** [sudharti/socify#5]
after all steps I get this error
Current ExecJS runtime does't support ES5. Please install node.js. (in C:/Sites/socify/app/assets/stylesheets/application.css.scss)

**Comment by nezirz** [comment]
You need to install Node.js 
http://stackoverflow.com/questions/28130096/how-can-i-fix-a-runtime-error-for-a-ruby-on-rails-app-using-a-windows-operating

Probably you are using some version of Linux OS:
https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager

https://rubygems.org/gems/node/versions/0.0.2

**Comment by moifouss** [comment]
Thanks, I ll try that and ses.
I using rails on win7 64

Envoyé à partir de mon Windows Phone

---

De : zirexbamailto:notifications@github.com
Envoyé : ‎11/‎09/‎2015 17:54
À : sudharti/socifymailto:socify@noreply.github.com
Cc : Fousseni Diarramailto:jsfousseni@hotmail.com
Objet : Re: [socify] Note error (#5)

You need to install Node.js
http://stackoverflow.com/questions/28130096/how-can-i-fix-a-runtime-error-for-a-ruby-on-rails-app-using-a-windows-operating

Probably you are using some version of Linux OS:
https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager

https://rubygems.org/gems/node/versions/0.0.2

---

**Comment by moifouss** [comment]
I have node installed allready...
C:\Sites>cd socify
C:\Sites\socify>gem list node
**\* LOCAL GEMS ***
node (0.0.2)

**Comment by moifouss** [comment]
But still get the error

**Comment by nezirz** [comment]
no,  lets check this links if you use windows http://www.w3resource.com/node.js/installing-node.js-windows-and-linux.php

**Comment by moifouss** [comment]
I also installed nodejs (node-v4.0.0-x64.msi) on the computer

c:\dev\outils\nodejs>node --version
v4.0.0

**Comment by nezirz** [comment]
hmm..  I think that you will be really happy only if you use linux for rails programming or testing.
Download some of Ubuntu versions Virtual Machine install rails there.....

**Comment by moifouss** [comment]
I think so! -- But it's working fine now (I don't know why); maybe nodejs needs sometimes before working after the installation.
Thanks for trying to help me ;)

**Comment by nezirz** [comment]
hehe great,  yes, sometimes it need some restarts :D you're welcome ...

**Comment by scaffeinate** [comment]
Great work @zirexba. :+1:

**Comment by scaffeinate** [comment]
@moifouss You can close the issue if it is resolved

**Comment by nezirz** [comment]
Tnx @sudharti
