### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by augmen** [sudharti/socify#53]
After sucesfull installation of ROR and posgresQL : I have run the command 👍 
`git clone https://github.com/sudharti/socify
cd socify
bundle install`

got this error 

![screen shot 2017-08-05 at 15 31 47](https://user-images.githubusercontent.com/11497036/28994755-3dab4d8c-79f3-11e7-98b8-7c1473c3b91c.png)

The i creat new sudo user by running 👍 
`adduser swap2`
`su - swap2`
i dropped into 

> swap2@soucify
As my instance name is socify

Than i tried to `cd socify` but didn't get it 

Then i run the above mentioned command as sudo user 👍 

`sudo apt install ruby-bundler`
`rake db:create`
got this error
![screen shot 2017-08-05 at 16 04 03](https://user-images.githubusercontent.com/11497036/28994919-26831450-79f8-11e7-960b-755e17b98c3a.png)
![screen shot 2017-08-05 at 16 04 03](https://user-images.githubusercontent.com/11497036/28994921-32137954-79f8-11e7-9e43-88ab136102c8.png)

`sudo apt install ruby-railties`

i think i am going wrong . how to run the commands 

`bundle install`
`rake db:create`
`rails server`

As sudo -user ? I hope that you got it.

I just added the rake gem 
`gem install rake `
and run the command 

`bundle install`

got this error 

![screen shot 2017-08-05 at 18 40 33](https://user-images.githubusercontent.com/11497036/28995703-fbd31d3e-7a0d-11e7-8c53-56fd933fe1e5.png)

Try to install the rake from bundle install rake. But got this error

![screen shot 2017-08-05 at 18 52 31](https://user-images.githubusercontent.com/11497036/28995792-2aaf272c-7a10-11e7-891a-69dffdc2fbad.png)

After installing rake and running the command `rake db:create` got this 👍 
![screen shot 2017-08-05 at 18 56 40](https://user-images.githubusercontent.com/11497036/28995787-fb85e5d0-7a0f-11e7-836b-edf1ff7fec24.png)

Thanks

**Comment by scaffeinate** [comment]
@augmen I think you are not understanding what rake is. You don't have to setup```rake``` manually. It will be setup when you install  rails. 

You are getting the error because it's ```rake db:migrate``` not ```rake db:create```. And also please don't run bundle commands using ```sudo```. Your first screenshot indicates you are running as root(```root@socify```). Please create a user and install ruby and rails.

Looks like there is a mismatch between the bundler & ruby version of your system and the one specified in the Gemfile.

Try reinstalling ruby and rails. Use this https://gorails.com/setup/.

**Comment by scaffeinate** [comment]
@augmen This looks like a config problem on your system. Since it's not anything specific to the app itself am closing this issue. Please feel free to ask any questions in this thread.

**Comment by augmen** [comment]
I am using the Ruby 2.3.1 & Rails 5.1.3. Ok i got it `rake db:migrate`. You mean to create a `sudo user `and then instal ROR as sudo user ? is yes then please guide us on the commands guide if possible ? 
Thanks

**Comment by scaffeinate** [comment]
@augmen You can create a sudo user. I was just saying don't install ruby/rails as the root user or use sudo commands for rails/bundler specific commands.

**Comment by augmen** [comment]
@scaffeinate what is the sudo command for the `bundle install` ? as i was getting error not to run `bundle install` as root user.

**Comment by scaffeinate** [comment]
@augmen You aren't supposed to run it as root

**Comment by augmen** [comment]
@scaffeinate  So run with sudo command or run as sudo user ?

**Comment by scaffeinate** [comment]
@augmen No just run without the sudo. And also not as the root user. Run it without any elevated privileges.

**Comment by augmen** [comment]
@scaffeinate i run it as `bundle install ` and got this 
![screen shot 2017-08-05 at 15 31 47](https://user-images.githubusercontent.com/11497036/29000621-5aac7604-7a8e-11e7-8de9-405c72e97293.png)

Please look @ bundle install command return.
Any direct code

**Comment by scaffeinate** [comment]
@augmen Can't you see **root@soucify**. You are clearly as the root

**Comment by augmen** [comment]
@scaffeinate Yes which directory to change ? as not root user ? 
Shall i try by creating sudo user ? like this 
The i creat new sudo user by running 👍
adduser swap2
su - swap2
i dropped into

swap2@soucify

but i didn't get into  app  as sudo user?

**Comment by scaffeinate** [comment]
@augmen It's not the directory. You are logged in as the root user. Please create a new user and switch to it. Or did you use ```sudo su```?

**Comment by augmen** [comment]
@scaffeinate  Got it . Create a sudo user and `sudo su` then  install ROR following the guide @ gorillas.com and then run `bundle install`. Thanks

**Comment by scaffeinate** [comment]
@augmen No. That's exactly what you aren't supposed to do. I asked you whether you did it to switch as the root user. Please create a new user(Not a root) then install ROR.

**Comment by augmen** [comment]
@scaffeinate to switch user i did  -`adduser - swap2` then `su -swap2` to switch to non-root user.  then `sudo su` & `cd` to switch to root user. As a non-root user you cannot `cd socify` ? therefore to run the `bundle install` command inside the `cd socify` you should use as root user !!.   I am using the same gorails.com  guide to setup the engine . Also tried the same with digital ocean one click ROR apps. But results are same.

**Comment by scaffeinate** [comment]
@augmen  I am not sure what issue you are facing. Maybe use this guide to set your server up: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04. And use this to install: https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04. It's a step-by-step tutorial to get it up and running :)

**Comment by augmen** [comment]
@scaffeinate @scaffeinate to switch user i did -adduser - swap2 then su -swap2 to switch to non-root user. then sudo su & cd to switch to root user. As a non-root user you cannot cd socify ? therefore to run the bundle install command inside the cd socify you should use as root user !!. I am using the same gorails.com guide to setup the engine . Also tried the same with digital ocean one click ROR apps. But results are same.

**Comment by scaffeinate** [comment]
@augmen It's because you cloned the project as the root user and trying to access as a non-root user. Simple permission issue. I would suggest to go over the links and start over server setup. But it's up to you

**Comment by augmen** [comment]
ok i will try thanks appreciated

**Comment by augmen** [comment]
i switched to sudo user it looks like this.
![screen shot 2017-08-06 at 10 34 20](https://user-images.githubusercontent.com/11497036/29000748-ef4f6736-7a92-11e7-852d-3f760666a61f.png)

then i tries to clone  install socify  as non-root user
`git clone https://github.com/sudharti/socify
`
got error Permission denied ?

**Comment by augmen** [comment]
i still fail ? do you have copy of your script / source code that you can share . will use AWS elastic beanstalk to launch the code directly ?

**Comment by scaffeinate** [comment]
@augmen I couldn't help but notice that you are trying to clone the project as a non-root user but in the **/root** directory(which is system directory and ofcourse restricted). I suggest you checkout the unix man-page first before trying to configure your env. And I don't have any script as such. All I had were the links I shared.

**Comment by augmen** [comment]
I succeeded & resolved the `bundle install ` . But could not get the app live in browser local hosts 3000 . I run the command `rails serve` and got this
![screen shot 2017-08-08 at 14 22 28](https://user-images.githubusercontent.com/11497036/29064027-5683ee00-7c45-11e7-8bf6-de8b68a75398.png)

**Comment by scaffeinate** [comment]
Localhost :rofl: :rofl:. Localhost indicates your local computer. https://en.wikipedia.org/wiki/Localhost. If you are starting on a server you need to access it through it's IP address or domain name if you have done a DNS mapping. I think it's best for you to read about web dev basics before trying to deploy.
