### ISSUE TITLE
Error when rake fill:data

### ISSUE THREAD

**Issue by moifouss** [sudharti/socify#6]
C:\Sites\socify>rake fill:data
# Erasing existing data

rake aborted!
NoMethodError: undefined method `auto_html_for' for Post (call 'Post.connection' to establish a connection):Class
C:/Sites/socify/app/models/post.rb:23:in`class:Post'
C:/Sites/socify/app/models/post.rb:5:in `<top (required)>'
C:/Sites/socify/lib/tasks/populate.rake:9:in`block (2 levels) in <top (required)>'
Tasks: TOP => fill:data
(See full trace by running task with --trace)

**Comment by nezirz** [comment]
https://github.com/dejan/auto_html/issues/140      or     https://github.com/dejan/auto_html/issues/8

**Comment by moifouss** [comment]
I installed auto_html but the error is still there

C:\Sites\socify>gem list auto_html
**\* LOCAL GEMS ***
auto_html (1.6.4, 1.6.0)

**Comment by nezirz** [comment]
tried restart?

**Comment by moifouss** [comment]
Yes, I restarted the server

**Comment by scaffeinate** [comment]
@moifouss Check the version of auto_html in Gemfile.lock

**Comment by moifouss** [comment]
I added gem 'auto_html','~>1.6.4' to my gem file and did bundle and "rake fill:data" and hop!
Everything is ok now.
It was not easy making that run on windows but I'm very happy (As I'm new to RoR) to make that work.
Thanks for all
