### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by Progklui** [sudharti/socify#9]
I got a clone of the project and tried to run it.

When connecting to localhost:3000 I get the error ActiveRecord::PendingMigrationError. 
I tried to fix it but nothing worked.

Could you help me with this error?

**Comment by scaffeinate** [comment]
@Progklui Did you run rake db:migrate?

**Comment by Progklui** [comment]
Yes, I followed the steps described on your blog and on github.

**Comment by Progklui** [comment]
Hi,

I have found my mistake. I have installed rake version 10.5.0 on my system but your Gemfile requires rake version 10.4.2. 
After uninstalling version 10.5.0 and installing 10.4.2 everything works fine.

Great app!!

**Comment by scaffeinate** [comment]
@Progklui Thank you :+1:
